/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ManagerRouteImport } from './routes/manager'
import { Route as GeneratingRouteImport } from './routes/generating'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CourseCourseIdRouteImport } from './routes/course.$courseId'
import { Route as CourseCourseIdIndexRouteImport } from './routes/course.$courseId.index'
import { Route as CourseCourseIdRoleplayRouteImport } from './routes/course.$courseId.roleplay'
import { Route as CourseCourseIdCompleteRouteImport } from './routes/course.$courseId.complete'
import { Route as CourseCourseIdCertificateRouteImport } from './routes/course.$courseId.certificate'
import { Route as CourseCourseIdSectionSectionIdRouteImport } from './routes/course.$courseId.section.$sectionId'
import { Route as CourseCourseIdSectionSectionIdIndexRouteImport } from './routes/course.$courseId.section.$sectionId.index'
import { Route as CourseCourseIdSectionSectionIdQuizRouteImport } from './routes/course.$courseId.section.$sectionId.quiz'

const ManagerRoute = ManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => rootRouteImport,
} as any)
const GeneratingRoute = GeneratingRouteImport.update({
  id: '/generating',
  path: '/generating',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseCourseIdRoute = CourseCourseIdRouteImport.update({
  id: '/course/$courseId',
  path: '/course/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseCourseIdIndexRoute = CourseCourseIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CourseCourseIdRoute,
} as any)
const CourseCourseIdRoleplayRoute = CourseCourseIdRoleplayRouteImport.update({
  id: '/roleplay',
  path: '/roleplay',
  getParentRoute: () => CourseCourseIdRoute,
} as any)
const CourseCourseIdCompleteRoute = CourseCourseIdCompleteRouteImport.update({
  id: '/complete',
  path: '/complete',
  getParentRoute: () => CourseCourseIdRoute,
} as any)
const CourseCourseIdCertificateRoute =
  CourseCourseIdCertificateRouteImport.update({
    id: '/certificate',
    path: '/certificate',
    getParentRoute: () => CourseCourseIdRoute,
  } as any)
const CourseCourseIdSectionSectionIdRoute =
  CourseCourseIdSectionSectionIdRouteImport.update({
    id: '/section/$sectionId',
    path: '/section/$sectionId',
    getParentRoute: () => CourseCourseIdRoute,
  } as any)
const CourseCourseIdSectionSectionIdIndexRoute =
  CourseCourseIdSectionSectionIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => CourseCourseIdSectionSectionIdRoute,
  } as any)
const CourseCourseIdSectionSectionIdQuizRoute =
  CourseCourseIdSectionSectionIdQuizRouteImport.update({
    id: '/quiz',
    path: '/quiz',
    getParentRoute: () => CourseCourseIdSectionSectionIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/generating': typeof GeneratingRoute
  '/manager': typeof ManagerRoute
  '/course/$courseId': typeof CourseCourseIdRouteWithChildren
  '/course/$courseId/certificate': typeof CourseCourseIdCertificateRoute
  '/course/$courseId/complete': typeof CourseCourseIdCompleteRoute
  '/course/$courseId/roleplay': typeof CourseCourseIdRoleplayRoute
  '/course/$courseId/': typeof CourseCourseIdIndexRoute
  '/course/$courseId/section/$sectionId': typeof CourseCourseIdSectionSectionIdRouteWithChildren
  '/course/$courseId/section/$sectionId/quiz': typeof CourseCourseIdSectionSectionIdQuizRoute
  '/course/$courseId/section/$sectionId/': typeof CourseCourseIdSectionSectionIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/generating': typeof GeneratingRoute
  '/manager': typeof ManagerRoute
  '/course/$courseId/certificate': typeof CourseCourseIdCertificateRoute
  '/course/$courseId/complete': typeof CourseCourseIdCompleteRoute
  '/course/$courseId/roleplay': typeof CourseCourseIdRoleplayRoute
  '/course/$courseId': typeof CourseCourseIdIndexRoute
  '/course/$courseId/section/$sectionId/quiz': typeof CourseCourseIdSectionSectionIdQuizRoute
  '/course/$courseId/section/$sectionId': typeof CourseCourseIdSectionSectionIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/generating': typeof GeneratingRoute
  '/manager': typeof ManagerRoute
  '/course/$courseId': typeof CourseCourseIdRouteWithChildren
  '/course/$courseId/certificate': typeof CourseCourseIdCertificateRoute
  '/course/$courseId/complete': typeof CourseCourseIdCompleteRoute
  '/course/$courseId/roleplay': typeof CourseCourseIdRoleplayRoute
  '/course/$courseId/': typeof CourseCourseIdIndexRoute
  '/course/$courseId/section/$sectionId': typeof CourseCourseIdSectionSectionIdRouteWithChildren
  '/course/$courseId/section/$sectionId/quiz': typeof CourseCourseIdSectionSectionIdQuizRoute
  '/course/$courseId/section/$sectionId/': typeof CourseCourseIdSectionSectionIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/generating'
    | '/manager'
    | '/course/$courseId'
    | '/course/$courseId/certificate'
    | '/course/$courseId/complete'
    | '/course/$courseId/roleplay'
    | '/course/$courseId/'
    | '/course/$courseId/section/$sectionId'
    | '/course/$courseId/section/$sectionId/quiz'
    | '/course/$courseId/section/$sectionId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/generating'
    | '/manager'
    | '/course/$courseId/certificate'
    | '/course/$courseId/complete'
    | '/course/$courseId/roleplay'
    | '/course/$courseId'
    | '/course/$courseId/section/$sectionId/quiz'
    | '/course/$courseId/section/$sectionId'
  id:
    | '__root__'
    | '/'
    | '/generating'
    | '/manager'
    | '/course/$courseId'
    | '/course/$courseId/certificate'
    | '/course/$courseId/complete'
    | '/course/$courseId/roleplay'
    | '/course/$courseId/'
    | '/course/$courseId/section/$sectionId'
    | '/course/$courseId/section/$sectionId/quiz'
    | '/course/$courseId/section/$sectionId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GeneratingRoute: typeof GeneratingRoute
  ManagerRoute: typeof ManagerRoute
  CourseCourseIdRoute: typeof CourseCourseIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/manager': {
      id: '/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof ManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generating': {
      id: '/generating'
      path: '/generating'
      fullPath: '/generating'
      preLoaderRoute: typeof GeneratingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course/$courseId': {
      id: '/course/$courseId'
      path: '/course/$courseId'
      fullPath: '/course/$courseId'
      preLoaderRoute: typeof CourseCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course/$courseId/': {
      id: '/course/$courseId/'
      path: '/'
      fullPath: '/course/$courseId/'
      preLoaderRoute: typeof CourseCourseIdIndexRouteImport
      parentRoute: typeof CourseCourseIdRoute
    }
    '/course/$courseId/roleplay': {
      id: '/course/$courseId/roleplay'
      path: '/roleplay'
      fullPath: '/course/$courseId/roleplay'
      preLoaderRoute: typeof CourseCourseIdRoleplayRouteImport
      parentRoute: typeof CourseCourseIdRoute
    }
    '/course/$courseId/complete': {
      id: '/course/$courseId/complete'
      path: '/complete'
      fullPath: '/course/$courseId/complete'
      preLoaderRoute: typeof CourseCourseIdCompleteRouteImport
      parentRoute: typeof CourseCourseIdRoute
    }
    '/course/$courseId/certificate': {
      id: '/course/$courseId/certificate'
      path: '/certificate'
      fullPath: '/course/$courseId/certificate'
      preLoaderRoute: typeof CourseCourseIdCertificateRouteImport
      parentRoute: typeof CourseCourseIdRoute
    }
    '/course/$courseId/section/$sectionId': {
      id: '/course/$courseId/section/$sectionId'
      path: '/section/$sectionId'
      fullPath: '/course/$courseId/section/$sectionId'
      preLoaderRoute: typeof CourseCourseIdSectionSectionIdRouteImport
      parentRoute: typeof CourseCourseIdRoute
    }
    '/course/$courseId/section/$sectionId/': {
      id: '/course/$courseId/section/$sectionId/'
      path: '/'
      fullPath: '/course/$courseId/section/$sectionId/'
      preLoaderRoute: typeof CourseCourseIdSectionSectionIdIndexRouteImport
      parentRoute: typeof CourseCourseIdSectionSectionIdRoute
    }
    '/course/$courseId/section/$sectionId/quiz': {
      id: '/course/$courseId/section/$sectionId/quiz'
      path: '/quiz'
      fullPath: '/course/$courseId/section/$sectionId/quiz'
      preLoaderRoute: typeof CourseCourseIdSectionSectionIdQuizRouteImport
      parentRoute: typeof CourseCourseIdSectionSectionIdRoute
    }
  }
}

interface CourseCourseIdSectionSectionIdRouteChildren {
  CourseCourseIdSectionSectionIdQuizRoute: typeof CourseCourseIdSectionSectionIdQuizRoute
  CourseCourseIdSectionSectionIdIndexRoute: typeof CourseCourseIdSectionSectionIdIndexRoute
}

const CourseCourseIdSectionSectionIdRouteChildren: CourseCourseIdSectionSectionIdRouteChildren =
  {
    CourseCourseIdSectionSectionIdQuizRoute:
      CourseCourseIdSectionSectionIdQuizRoute,
    CourseCourseIdSectionSectionIdIndexRoute:
      CourseCourseIdSectionSectionIdIndexRoute,
  }

const CourseCourseIdSectionSectionIdRouteWithChildren =
  CourseCourseIdSectionSectionIdRoute._addFileChildren(
    CourseCourseIdSectionSectionIdRouteChildren,
  )

interface CourseCourseIdRouteChildren {
  CourseCourseIdCertificateRoute: typeof CourseCourseIdCertificateRoute
  CourseCourseIdCompleteRoute: typeof CourseCourseIdCompleteRoute
  CourseCourseIdRoleplayRoute: typeof CourseCourseIdRoleplayRoute
  CourseCourseIdIndexRoute: typeof CourseCourseIdIndexRoute
  CourseCourseIdSectionSectionIdRoute: typeof CourseCourseIdSectionSectionIdRouteWithChildren
}

const CourseCourseIdRouteChildren: CourseCourseIdRouteChildren = {
  CourseCourseIdCertificateRoute: CourseCourseIdCertificateRoute,
  CourseCourseIdCompleteRoute: CourseCourseIdCompleteRoute,
  CourseCourseIdRoleplayRoute: CourseCourseIdRoleplayRoute,
  CourseCourseIdIndexRoute: CourseCourseIdIndexRoute,
  CourseCourseIdSectionSectionIdRoute:
    CourseCourseIdSectionSectionIdRouteWithChildren,
}

const CourseCourseIdRouteWithChildren = CourseCourseIdRoute._addFileChildren(
  CourseCourseIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GeneratingRoute: GeneratingRoute,
  ManagerRoute: ManagerRoute,
  CourseCourseIdRoute: CourseCourseIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
